### ISSUE TITLE
Issue with `bash prepare-deps.sh`

### ISSUE THREAD

**Issue by bnsilvaa** [alvr-org/alvr-gearvr-go#1]
Hi, I'm having an issue while running `bash prepare-deps.sh`. I don't know if I'm missing some package on linux.

>...
  creating: ALVR-master/wiki/images/
  inflating: ALVR-master/wiki/images/ALVR-audio-crash.png
  inflating: ALVR-master/wiki/images/ALVRexe-404.png
  inflating: ALVR-master/wiki/images/ALVRexe-no-clients.png
  inflating: ALVR-master/wiki/images/SteamVR-add-ons.png
  inflating: ALVR-master/wiki/images/SteamVR-headset-not-detected.png
  inflating: ALVR-master/wiki/images/SteamVR-waiting.png
/home/bnsilva/alvr-gearvr-main/ALVR /home/bnsilva/alvr-gearvr-main
error: failed to load manifest for workspace member '/home/bnsilva/alvr-gearvr-main/ALVR/alvr/audio'
Caused by:
  failed to parse manifest at '/home/bnsilva/alvr-gearvr-main/ALVR/alvr/audio/Cargo.toml'
Caused by:
  invalid type: map, expected a string for key 'package.rust-version'

**Comment by zmerp** [comment]
Update Rust: `rustup update`

**Comment by bnsilvaa** [comment]
Thank you for the help! I'm still having the same issue, but I will try again on another machine to check if it solve the issue.

> rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active 'rustc' version is 'rustc 1.67.0 (fc594f156 2023-01-24)'
